const $=s=>document.querySelector(s);let view='firestore',docs=[],collectionPath='',selectedDoc='';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function notice(message,error=false){const n=$('#notice');n.textContent=message;n.className=message?'show'+(error?' error':''):''}
async function get(url,options){const response=await fetch(url,options);const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||`Request failed (${response.status})`);return body}
function project(){return $('#project').value.trim()}function q(s){return encodeURIComponent(s)}
document.querySelectorAll('nav button').forEach(button=>button.onclick=()=>{view=button.dataset.view;document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===button));document.querySelectorAll('main section').forEach(x=>x.hidden=x.id!==view);refresh()});
$('#refresh').onclick=refresh;$('#database').onchange=()=>{collectionPath='';selectedDoc='';refreshFirestore()};
async function refresh(){notice('');try{if(view==='auth')await refreshAuth();if(view==='firestore')await refreshFirestore();if(view==='pubsub')await refreshPubsub()}catch(e){notice(e.message,true)}}
async function init(){const c=await get('/api/config');$('#project').value=c.defaultProject;await refresh()}

async function refreshAuth(){const body=await get(`/api/auth/users?project=${q(project())}`),users=body.users||[];$('#users').innerHTML=users.length?users.map((u,i)=>`<button data-i="${i}">${esc(u.email||u.phoneNumber||u.localId)}</button>`).join(''):'<div class="empty">No users in this project.</div>';$('#userDetail').className='empty';$('#userDetail').textContent='Select a user to inspect its record.';$('#users').querySelectorAll('button').forEach(b=>b.onclick=()=>showUser(users[+b.dataset.i],b))}
function showUser(user,button){$('#users').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===button));let claims=user.customAttributes;try{claims=claims?JSON.parse(claims):{}}catch{}const rows={UID:user.localId,Email:user.email||'—','Email verified':user.emailVerified,Phone:user.phoneNumber||'—','Display name':user.displayName||'—',Disabled:user.disabled,'Created at':user.createdAt,'Last login':user.lastLoginAt};$('#userDetail').className='detail';$('#userDetail').innerHTML=`<h3>${esc(user.localId)}</h3><div class="card"><dl>${Object.entries(rows).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl></div><h2>Custom claims</h2><pre class="value">${esc(JSON.stringify(claims,null,2))}</pre>`}

function relative(d){return d.name.split('/documents/')[1]}function parts(d){return relative(d).split('/')}
function rootCollections(){return [...new Set(docs.map(d=>parts(d)[0]))].sort()}
function immediateDocs(path){const p=path.split('/');return docs.filter(d=>{const x=parts(d);return x.length===p.length+1&&p.every((v,i)=>x[i]===v)})}
function nestedCollections(path){const p=path.split('/');return [...new Set(docs.filter(d=>{const x=parts(d);return x.length>p.length&&p.every((v,i)=>x[i]===v)}).map(d=>parts(d)[p.length]))].sort()}
async function refreshFirestore(){const body=await get(`/api/firestore/documents?project=${q(project())}&database=${q($('#database').value.trim())}`);docs=body.documents||[];renderFirestore()}
function clearDocument(){const d=$('#docDetail');d.className='empty';d.textContent='Choose a collection and document.'}
function renderFirestore(){const collections=collectionPath?nestedCollections(selectedDoc):rootCollections();$('#collections').innerHTML=collections.length?collections.map(c=>`<button data-c="${esc(c)}">${esc(c)}</button>`).join(''):'<div class="empty">No collections here.</div>';$('#collections').querySelectorAll('button').forEach(b=>b.onclick=()=>{collectionPath=selectedDoc?selectedDoc+'/'+b.dataset.c:b.dataset.c;selectedDoc='';clearDocument();renderFirestore()});const list=collectionPath?immediateDocs(collectionPath):[];$('#documents').innerHTML=list.length?list.map(d=>`<button data-p="${esc(relative(d))}">${esc(parts(d).at(-1))}</button>`).join(''):'<div class="empty">'+(collectionPath?'No documents in this collection.':'Choose a collection.')+'</div>';$('#documents').querySelectorAll('button').forEach(b=>b.onclick=()=>{selectedDoc=b.dataset.p;renderFirestore();showDocument(docs.find(d=>relative(d)===selectedDoc))});const segments=(selectedDoc||collectionPath).split('/').filter(Boolean);$('#crumbs').innerHTML='<button data-root>/(root)</button>'+segments.map((s,i)=>` / <button data-b="${i}">${esc(s)}</button>`).join('');$('#crumbs [data-root]').onclick=()=>{collectionPath='';selectedDoc='';clearDocument();renderFirestore()};$('#crumbs').querySelectorAll('[data-b]').forEach(b=>b.onclick=()=>{const i=+b.dataset.b;if(i%2===0){collectionPath=segments.slice(0,i+1).join('/');selectedDoc='';clearDocument()}else{selectedDoc=segments.slice(0,i+1).join('/');collectionPath=segments.slice(0,i).join('/')}renderFirestore();if(selectedDoc)showDocument(docs.find(d=>relative(d)===selectedDoc))})}
function fieldType(v){return Object.keys(v||{})[0]?.replace('Value','')||'null'}
function plain(v){const k=Object.keys(v||{})[0],x=v?.[k];if(k==='mapValue')return Object.fromEntries(Object.entries(x.fields||{}).map(([a,b])=>[a,plain(b)]));if(k==='arrayValue')return (x.values||[]).map(plain);if(k==='nullValue')return null;if(k==='integerValue')return x+' (int64)';if(k==='bytesValue')return x+' (base64)';return x}
function editorText(v){const k=Object.keys(v||{})[0],x=v?.[k];if(k==='nullValue')return'null';if(k==='arrayValue'||k==='mapValue'||k==='geoPointValue'||(k==='timestampValue'&&typeof x==='object'))return JSON.stringify(x,null,2);return String(x??'')}
function typedValue(original,text){const k=Object.keys(original||{})[0];if(k==='nullValue'){if(text.trim()!=='null')throw new Error('Null values must remain null.');return{nullValue:null}}if(k==='booleanValue'){if(!/^(true|false)$/i.test(text.trim()))throw new Error('Boolean values must be true or false.');return{booleanValue:text.trim().toLowerCase()==='true'}}if(k==='integerValue'){if(!/^-?\d+$/.test(text.trim()))throw new Error('Integer values must be whole decimal numbers.');return{integerValue:text.trim()}}if(k==='doubleValue'){const value=text.trim(),special=['NaN','Infinity','-Infinity'];if(!special.includes(value)&&(!value||!Number.isFinite(Number(value))))throw new Error('Enter a number, NaN, Infinity, or -Infinity.');return{doubleValue:special.includes(value)?value:Number(value)}}if(k==='arrayValue'||k==='mapValue'||k==='geoPointValue'){let value;try{value=JSON.parse(text)}catch{throw new Error(`${fieldType(original)} value must be valid JSON.`)}return{[k]:value}}if(k==='timestampValue'&&text.trim().startsWith('{')){let value;try{value=JSON.parse(text)}catch{throw new Error('Timestamp value must be valid JSON or an RFC 3339 timestamp.')}return{timestampValue:value}}return{[k]:text}}
function resizeEditor(input){input.style.height='0';input.style.height=Math.min(180,Math.max(30,input.scrollHeight))+'px'}
function showDocument(doc){if(!doc)return;const fields=Object.entries(doc.fields||{});$('#docDetail').className='detail';$('#docDetail').innerHTML=`<div class="document-head"><h3>${esc(relative(doc))}</h3><div class="toolbar"><button id="copyObject">Copy object</button><button id="openClone">Clone document</button></div></div><div class="fields">${fields.length?fields.map(([k,v],i)=>`<div class="field-row"><label for="field-${i}"><strong>${esc(k)}</strong><small>${esc(fieldType(v))}</small></label><textarea id="field-${i}" data-i="${i}" rows="1" spellcheck="false">${esc(editorText(v))}</textarea><button class="save-field" data-i="${i}" disabled>Save</button></div>`).join(''):'<div class="empty">Empty document</div>'}</div><p class="format-note">Edit values in place; types remain fixed. Arrays and maps use typed Firestore REST Value JSON internally. Copy object uses the same type-preserving representation.</p>`;$('#copyObject').onclick=async()=>{await navigator.clipboard.writeText(JSON.stringify(doc.fields||{},null,2));notice('Typed Firestore object copied.')};$('#openClone').onclick=()=>{const p=relative(doc).split('/');$('#cloneSource').textContent='Source: '+relative(doc);$('#cloneCollection').value=p.slice(0,-1).join('/');$('#cloneId').value=p.at(-1)+'-copy';$('#cloneChildren').checked=false;$('#cloneDialog').showModal()};$('#docDetail').querySelectorAll('textarea').forEach(input=>{resizeEditor(input);input.oninput=()=>{resizeEditor(input);input.closest('.field-row').querySelector('.save-field').disabled=input.value===editorText(fields[+input.dataset.i][1])};input.onkeydown=e=>{if(e.key==='Enter'&&(e.metaKey||e.ctrlKey)){e.preventDefault();input.closest('.field-row').querySelector('.save-field').click()}}});$('#docDetail').querySelectorAll('.save-field').forEach(button=>button.onclick=async()=>{const i=+button.dataset.i,[fieldName,original]=fields[i],input=$(`#field-${i}`);try{button.disabled=true;await get('/api/firestore/field',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({project:project(),database:$('#database').value.trim(),documentPath:relative(doc),fieldName,value:typedValue(original,input.value)})});notice(`${fieldName} saved.`);await refreshFirestore();const updated=docs.find(d=>relative(d)===selectedDoc);if(updated)showDocument(updated)}catch(e){button.disabled=false;notice(e.message,true)}})}
$('#cloneSubmit').onclick=async event=>{event.preventDefault();try{const result=await get('/api/firestore/clone',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({project:project(),database:$('#database').value.trim(),sourcePath:selectedDoc,destinationCollectionPath:$('#cloneCollection').value.trim(),destinationId:$('#cloneId').value.trim(),includeSubcollections:$('#cloneChildren').checked})});$('#cloneDialog').close();notice(`Cloned ${result.documentsCloned} document(s) to ${result.destinationPath}.`);await refreshFirestore()}catch(e){notice(e.message,true)}};

async function refreshPubsub(){const body=await get(`/api/pubsub?project=${q(project())}`),topics=body.topics||[];$('#topics').innerHTML=topics.length?topics.map((t,i)=>`<button data-i="${i}">${esc(t.name.split('/').at(-1))}<small>${t.subscriptions.length} subscription(s)</small></button>`).join(''):'<div class="empty">No topics in this project.</div>';$('#topicDetail').className='empty';$('#topicDetail').textContent='Select a topic to inspect its configuration.';$('#topics').querySelectorAll('button').forEach(b=>b.onclick=()=>showTopic(topics[+b.dataset.i],b))}
function showTopic(topic,button){$('#topics').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===button));$('#topicDetail').className='detail';$('#topicDetail').innerHTML=`<h3>${esc(topic.name)}</h3><div class="card"><pre class="value">${esc(JSON.stringify({labels:topic.labels,messageRetentionDuration:topic.messageRetentionDuration,state:topic.state},null,2))}</pre></div><h2>Associated subscriptions</h2>${topic.subscriptions.length?topic.subscriptions.map(s=>`<div class="card"><strong>${esc(s.name)}</strong><pre class="value">${esc(JSON.stringify(s,null,2))}</pre></div>`).join(''):'<div class="empty">No subscriptions.</div>'}`}
init().catch(e=>notice(e.message,true));
