import { ActionType, validateActionType } from './schema';
import React, { useEffect, useRef, useState } from 'react';
import { bounded } from './config';
export default function App({ client }) {
  const [email, setEmail] = useState('tester@example.test'); const [password, setPassword] = useState('test-password');
  const [id, setId] = useState('note-1'); const [file, setFile] = useState(null); const [status, setStatus] = useState('Ready'); const [busy, setBusy] = useState(false); const stop = useRef(null);
  useEffect(() => () => stop.current?.(), []);
  async function run(name, action) { setBusy(true); setStatus(`${name}: running`); try { const value = await bounded(Promise.resolve().then(action)); setStatus(`${name}: passed${value === undefined ? '' : ` ${JSON.stringify(value?.user ? { uid: value.user.uid } : value)}`}`); } catch (error) { setStatus(`${name}: failed — ${error.message}`); } finally { setBusy(false); } }
  const button = (name, action) => <button disabled={busy} onClick={() => run(name, action)}>{name}</button>;
  return <main><h1>Firebase browser test</h1><p>Local project: {client.settings.projectId}. These controls use the real Firebase browser SDK.</p><fieldset><legend>Synthetic input</legend>{button('Validate input', () => validateActionType(ActionType.UPDATE))}</fieldset><fieldset><legend>Authentication</legend><label>Email <input value={email} onChange={event => setEmail(event.target.value)} /></label><label>Password <input type="password" value={password} onChange={event => setPassword(event.target.value)} /></label>{button('Sign up', () => client.signUp(email, password))}{button('Sign in', () => client.signIn(email, password))}{button('Sign out', () => client.signOut())}</fieldset><fieldset><legend>Firestore</legend><label>Document ID <input value={id} onChange={event => setId(event.target.value)} /></label>{button('Create', () => client.create(id))}{button('Read', () => client.read(id))}{button('Update', () => client.update(id))}{button('Query', () => client.query(0))}{button('Delete', () => client.remove(id))}{button('Listen', () => { stop.current?.(); return new Promise((resolve, reject) => { stop.current = client.listen(id, value => { setStatus(`Snapshot: ${JSON.stringify(value)}`); resolve(value); }, reject); }); })}<button onClick={() => { stop.current?.(); stop.current = null; setStatus('Listener stopped'); }}>Stop listener</button></fieldset><fieldset><legend>Storage</legend><label>File <input type="file" onChange={event => setFile(event.target.files[0])} /></label>{button('Upload', () => { if (!file) throw new Error('Select a file.'); return client.upload('browser-demo.txt', file).then(() => undefined); })}{button('Download', () => client.download('browser-demo.txt'))}{button('Delete file', () => client.deleteFile('browser-demo.txt'))}</fieldset><pre role="status" aria-live="polite" data-testid="operation-status">{status}</pre></main>;
}
